### ISSUE TITLE
注释修改

### ISSUE THREAD

**Issue by wangzhenyujiang** [qbhy/go-tumblr-crawler#1]
// 设置最大协程数
maxProcesses := runtime.NumCPU() //获取cpu个数
runtime.GOMAXPROCS(maxProcesses) //限制同时运行的goroutines数量

runtime.GOMAXPROCS(maxProcesses) 这句代码是限制了线程的数量，而不是限制了 goroutines 的数量

**Comment by qbhy** [comment]
谢谢提醒，不过这里的意思应该是一样的。
正常情况下一个cpu对象启一个工作线程对象，线程去检查并执行goroutine对象。碰到goroutine对象阻塞的时候，会启动一个新的工作线程，以充分利用cpu资源。
还有我在考虑这个场景下不限制协程数量会不会更好，不知道你有没有建议 ？

**Comment by wangzhenyujiang** [comment]
现在 Go 已经默认设置 GOMAXPROCS 为当前机器从 CPU 数，所以这段代码可以不用写。之前的注释问题，因为 GO Runtime 是用 M-P-G 的调度模式，所以“限制**同时**运行的 goroutines 数量”的注释是正确的。

**Comment by qbhy** [comment]
谢谢提醒~
